### ISSUE TITLE
Create Acknowledgements List

### ISSUE THREAD

**Issue by andrewbwm** [mal-lang/coreLang#101]
Decide upon and create a comprehensive acknowledgements list for the people that helped out on the paper over the years.

**Comment by skatsikeas** [comment]
Here is the draft list of acknowledgements:

Main contributors (alphabetically after first two):

- Sotirios Katsikeas
- Andrei Buhaiu
- Zeeshan Afzal
- Mathias Ekstedt
- Simon Hacks
- Preetam Mukherjee

Past contributors:

KTH
- Robert Lagerström
- Pontus Johnson
- Ismail Butun

foreseeti (no particular order)
- Per Eliasson
- Joar Jacobsson
- Erik Ringdahl
- Max Wällstedt
- Victor Wallin

**Comment by skatsikeas** [comment]
- [ ] Add the contributor's list on GitHub (where?)

**Comment by andrewbwm** [comment]
> * [ ]  Add the contributor's list on GitHub (where?)

I think we can just create a file in the root directory called CONTRIBUTORS and just add all of those names there.

**Comment by skatsikeas** [comment]
The contributors are now listed in the [coreLang contributors page](https://mal-lang.org/coreLang/contributors.html).
