### ISSUE TITLE
Credential hashing

### ISSUE THREAD

**Issue by skatsikeas** [mal-lang/coreLang#17]
Can we model Credential hashing?

**Comment by skatsikeas** [comment]
I think we can! This is close to what Max did in the OAuth test model. He used two `Credential` instances and one `Data`. The (hashed) `Credentials` are contained inside `Data` and `Data` is in turn encrypted using the other `Credential` instance which is the hashing key.

**Comment by skatsikeas** [comment]
I just found a note I had about credential hashing. What we want to model is: authentication tokens that can be passed around or used in place

**Comment by andrewbwm** [comment]
Implemented in #63.
