### ISSUE TITLE
Data-in-Data readonly-access?

### ISSUE THREAD

**Issue by jesajx** [mal-lang/coreLang#32]
Hi, I think I might have found a bug (unless I'm missing something).

Some failing tests to demonstrate the bug can be found [here](https://github.com/jesajx/coreLang/blob/data-in-data-bug/src/test/java/org/mal_lang/corelang/test/DataPrivilegesTest.java). See `// TODO fails`.

Essentially, let there be two `Data`-assets named `X` and `Y`. Also let `X.containedData = {Y}`. Then we have that: `X.identityRead` implies `Y.write` -- which I think is a bug.

I think the problem is the edge `readContainedDataAndInformation -> containedData.attemptAccess`, but I'm not sure.  Most likely the read-flow through `Data` needs to be split up into multiple flows such that the privileges of `X` are correctly passed on to `Y`. Right now the privilege information gets lost along the way since all read-flows pass through `X.read`.

There is a related issue with the use of `Data.authenticated` defense. If `X.authenticated` but not `Y.authenticated` then the attacker (at `X.attemptAccess`) can reach `X.read` but not `X.write` (as expected). However, because the attacker can reach `X.read` they can also reach `Y.write` -- which I think is a bug. I was expecting the `X.authenticated` defense to also protect `Y` when the attacker is accessing `Y` through `X`.

**Comment by skatsikeas** [comment]
Those bugs are now fixed! Thank you for bringing them up.
And one question, can I include on the repo the test cases you have created?

**Comment by jesajx** [comment]
Great!
Yes, feel free to include them!

**Comment by skatsikeas** [comment]
Great, thank you.
